var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/mobile/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/[root-of-the-server]__0kvb4wt._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_mobile_route_actions_07~2ddd.js")
R.m(97072)
module.exports=R.m(97072).exports
