// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[locale]/(admin)/admin/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/branding">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/channels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/channels">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/channels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/chat-theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/chat-theme">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/chat-theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/gateways/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/gateways">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/gateways/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/plans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/plans/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/plans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/plans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/plans/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/plans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/plans">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/teams">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/admin/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/voice">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/analytics">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/automation/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automation/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/automation/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automation">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/calls">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/campaigns/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/campaigns/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/campaigns/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/campaigns/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/campaigns/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/campaigns">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contacts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/chat/[jid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/chat/[jid]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/chat/[jid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/inbox/chat/[jid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/inbox/chat/[jid]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/inbox/chat/[jid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/inbox">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/onboarding">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pipeline">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/activity">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/ai">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/connect">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/developers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/developers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/developers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/general">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/security">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/voice">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/templates/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/templates">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(login)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(login)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(login)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reset-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(login)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(login)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-in">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(login)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(login)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-up">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(login)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/docs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/channels">> = Specific
  const handler = {} as typeof import("../../app/api/admin/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/gateways/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gateways">> = Specific
  const handler = {} as typeof import("../../app/api/admin/gateways/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/offline-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/offline-payments">> = Specific
  const handler = {} as typeof import("../../app/api/admin/offline-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/teams/assign-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/teams/assign-plan">> = Specific
  const handler = {} as typeof import("../../app/api/admin/teams/assign-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/voice">> = Specific
  const handler = {} as typeof import("../../app/api/admin/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/mobile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mobile">> = Specific
  const handler = {} as typeof import("../../app/api/auth/mobile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/automation/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/upload">> = Specific
  const handler = {} as typeof import("../../app/api/automation/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branding">> = Specific
  const handler = {} as typeof import("../../app/api/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/credits/purchase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/credits/purchase">> = Specific
  const handler = {} as typeof import("../../app/api/calls/credits/purchase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/credits">> = Specific
  const handler = {} as typeof import("../../app/api/calls/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/history">> = Specific
  const handler = {} as typeof import("../../app/api/calls/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/initiate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/initiate">> = Specific
  const handler = {} as typeof import("../../app/api/calls/initiate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/numbers/mine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/numbers/mine">> = Specific
  const handler = {} as typeof import("../../app/api/calls/numbers/mine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/numbers/purchase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/numbers/purchase">> = Specific
  const handler = {} as typeof import("../../app/api/calls/numbers/purchase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/numbers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/numbers">> = Specific
  const handler = {} as typeof import("../../app/api/calls/numbers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/recording/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/recording">> = Specific
  const handler = {} as typeof import("../../app/api/calls/recording/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/calls/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calls/token">> = Specific
  const handler = {} as typeof import("../../app/api/calls/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/create">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/list">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/process">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/send">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/channels/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/channels/status">> = Specific
  const handler = {} as typeof import("../../app/api/channels/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat-theme">> = Specific
  const handler = {} as typeof import("../../app/api/chat-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/[id]/ai-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/[id]/ai-status">> = Specific
  const handler = {} as typeof import("../../app/api/chats/[id]/ai-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/[id]/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/[id]/close">> = Specific
  const handler = {} as typeof import("../../app/api/chats/[id]/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/[id]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/[id]/logs">> = Specific
  const handler = {} as typeof import("../../app/api/chats/[id]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/chats/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/[id]/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/[id]/session">> = Specific
  const handler = {} as typeof import("../../app/api/chats/[id]/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/delete">> = Specific
  const handler = {} as typeof import("../../app/api/chats/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/mark-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/mark-read">> = Specific
  const handler = {} as typeof import("../../app/api/chats/mark-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/media">> = Specific
  const handler = {} as typeof import("../../app/api/chats/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats">> = Specific
  const handler = {} as typeof import("../../app/api/chats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/assign-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/assign-agent">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/assign-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/assign-department/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/assign-department">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/assign-department/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/funnel-stage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/funnel-stage">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/funnel-stage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/notes">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/tags/[tagId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/tags/[tagId]">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/tags/[tagId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/[id]/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/tags">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/[id]/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/by-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/by-chat">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/by-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/import">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/list">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/move-instance-by-instance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/move-instance-by-instance">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/move-instance-by-instance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/move-instance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/move-instance">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/move-instance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts">> = Specific
  const handler = {} as typeof import("../../app/api/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/custom-fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-fields">> = Specific
  const handler = {} as typeof import("../../app/api/custom-fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/departments/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departments/[id]/members">> = Specific
  const handler = {} as typeof import("../../app/api/departments/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/departments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departments/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/departments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/departments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departments">> = Specific
  const handler = {} as typeof import("../../app/api/departments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features">> = Specific
  const handler = {} as typeof import("../../app/api/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/funnel-stages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funnel-stages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/funnel-stages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/funnel-stages/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funnel-stages/reorder">> = Specific
  const handler = {} as typeof import("../../app/api/funnel-stages/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/funnel-stages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funnel-stages">> = Specific
  const handler = {} as typeof import("../../app/api/funnel-stages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gateways/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gateways">> = Specific
  const handler = {} as typeof import("../../app/api/gateways/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/connect">> = Specific
  const handler = {} as typeof import("../../app/api/instance/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/delete">> = Specific
  const handler = {} as typeof import("../../app/api/instance/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/details/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/details">> = Specific
  const handler = {} as typeof import("../../app/api/instance/details/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/list">> = Specific
  const handler = {} as typeof import("../../app/api/instance/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/logout">> = Specific
  const handler = {} as typeof import("../../app/api/instance/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/meta-signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/meta-signup">> = Specific
  const handler = {} as typeof import("../../app/api/instance/meta-signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/qr/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/qr/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/instance/qr/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/qrcode">> = Specific
  const handler = {} as typeof import("../../app/api/instance/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/reconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/reconnect">> = Specific
  const handler = {} as typeof import("../../app/api/instance/reconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/rename/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/rename">> = Specific
  const handler = {} as typeof import("../../app/api/instance/rename/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/restart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/restart">> = Specific
  const handler = {} as typeof import("../../app/api/instance/restart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/setup">> = Specific
  const handler = {} as typeof import("../../app/api/instance/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/sync-chats/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/sync-chats/import">> = Specific
  const handler = {} as typeof import("../../app/api/instance/sync-chats/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/sync-chats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/sync-chats">> = Specific
  const handler = {} as typeof import("../../app/api/instance/sync-chats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/instance/sync-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instance/sync-messages">> = Specific
  const handler = {} as typeof import("../../app/api/instance/sync-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations">> = Specific
  const handler = {} as typeof import("../../app/api/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/react/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/react">> = Specific
  const handler = {} as typeof import("../../app/api/messages/react/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/send-template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/send-template">> = Specific
  const handler = {} as typeof import("../../app/api/messages/send-template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/send">> = Specific
  const handler = {} as typeof import("../../app/api/messages/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/sendAudio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/sendAudio">> = Specific
  const handler = {} as typeof import("../../app/api/messages/sendAudio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/sendMedia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/sendMedia">> = Specific
  const handler = {} as typeof import("../../app/api/messages/sendMedia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/complete">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/plan">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/status">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/workspace">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push-token">> = Specific
  const handler = {} as typeof import("../../app/api/push-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quick-replies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quick-replies">> = Specific
  const handler = {} as typeof import("../../app/api/quick-replies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime/typing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/typing">> = Specific
  const handler = {} as typeof import("../../app/api/realtime/typing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/ai/[id]/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/ai/[id]/action">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/ai/[id]/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/ai">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/automation/[id]/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/automation/[id]/action">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/automation/[id]/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/automation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/automation">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/automation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/twilio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/twilio">> = Specific
  const handler = {} as typeof import("../../app/api/settings/twilio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags">> = Specific
  const handler = {} as typeof import("../../app/api/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members">> = Specific
  const handler = {} as typeof import("../../app/api/team/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/membership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/membership">> = Specific
  const handler = {} as typeof import("../../app/api/team/membership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/templates/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/create">> = Specific
  const handler = {} as typeof import("../../app/api/templates/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/templates/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/list">> = Specific
  const handler = {} as typeof import("../../app/api/templates/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/templates/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/sync">> = Specific
  const handler = {} as typeof import("../../app/api/templates/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/delete">> = Specific
  const handler = {} as typeof import("../../app/api/user/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/password">> = Specific
  const handler = {} as typeof import("../../app/api/user/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user">> = Specific
  const handler = {} as typeof import("../../app/api/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/send">> = Specific
  const handler = {} as typeof import("../../app/api/v1/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/evolution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/evolution">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/evolution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/meta-cloud/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/meta-cloud">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/meta-cloud/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/razorpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/razorpay">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/razorpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/twilio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/twilio">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/twilio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/twilio/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/twilio/voice">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/twilio/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[locale]/(admin)/admin/branding/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin/branding">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/admin/branding/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/chat/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/chat">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/chat/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/inbox/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/inbox">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/inbox/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
