var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/calls/numbers/purchase/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/_098~pnw._.js")
R.c("server/chunks/node_modules_0x4yz9m._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/[root-of-the-server]__04n5b5w._.js")
R.c("server/chunks/node_modules_stripe_esm_stripe_esm_node_08xtjdd.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/node_modules_0tu5xat._.js")
R.c("server/chunks/_next-internal_server_app_api_calls_numbers_purchase_route_actions_0r-9hvx.js")
R.m(588731)
module.exports=R.m(588731).exports
