var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhook/evolution/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/[root-of-the-server]__0_1_sfx._.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/node_modules_0x4yz9m._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0j.fdeg._.js")
R.c("server/chunks/[root-of-the-server]__0sz9i60._.js")
R.c("server/chunks/_next-internal_server_app_api_webhook_evolution_route_actions_0q16zhf.js")
R.m(726993)
module.exports=R.m(726993).exports
