var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/chats/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0x4yz9m._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/[root-of-the-server]__06kgabi._.js")
R.c("server/chunks/_next-internal_server_app_api_chats_route_actions_0-k9kz..js")
R.m(587702)
module.exports=R.m(587702).exports
