var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/onboarding/plan/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0t2uf-n.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/_01_0w._._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/_next-internal_server_app_api_onboarding_plan_route_actions_0c~ea8x.js")
R.m(476392)
module.exports=R.m(476392).exports
