var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/gateways/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/[root-of-the-server]__0z7ctwo._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/_next-internal_server_app_api_gateways_route_actions_0z3ldgy.js")
R.m(228970)
module.exports=R.m(228970).exports
