var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/user/delete/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0e13cr..js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/node_modules_next_dist_04tjlp~._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_01_0w._._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/_next-internal_server_app_api_user_delete_route_actions_0o~sm_i.js")
R.m(834449)
module.exports=R.m(834449).exports
