var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/calls/recording/route.js")
R.c("server/chunks/[root-of-the-server]__1283e_2._.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/_01_0w._._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/_next-internal_server_app_api_calls_recording_route_actions_0h6npkg.js")
R.m(492213)
module.exports=R.m(492213).exports
