var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/branding/route.js")
R.c("server/chunks/[root-of-the-server]__12uhr4v._.js")
R.c("server/chunks/node_modules_next_dist_04tjlp~._.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_next-internal_server_app_api_branding_route_actions_02.8dvj.js")
R.m(432097)
module.exports=R.m(432097).exports
