var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/user/password/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0muodtd.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/node_modules_next_dist_04tjlp~._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_01_0w._._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/_next-internal_server_app_api_user_password_route_actions_0shmr0d.js")
R.m(507485)
module.exports=R.m(507485).exports
