var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhook/razorpay/route.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/[root-of-the-server]__0scfhy~._.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/_0hspxrq._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/node_modules_0x4yz9m._.js")
R.c("server/chunks/_098~pnw._.js")
R.c("server/chunks/node_modules_0tu5xat._.js")
R.c("server/chunks/node_modules_stripe_esm_stripe_esm_node_08xtjdd.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_next-internal_server_app_api_webhook_razorpay_route_actions_13o4ovi.js")
R.m(12242)
module.exports=R.m(12242).exports
