var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/calls/token/route.js")
R.c("server/chunks/[root-of-the-server]__0p9ra5~._.js")
R.c("server/chunks/[root-of-the-server]__0e3t.pb._.js")
R.c("server/chunks/[root-of-the-server]__0mp54xq._.js")
R.c("server/chunks/node_modules_semver_0yvutzv._.js")
R.c("server/chunks/node_modules_next_0x_x~l6._.js")
R.c("server/chunks/node_modules_next_dist_compiled_@opentelemetry_api_index_0uix5xn.js")
R.c("server/chunks/node_modules_0tu5xat._.js")
R.c("server/chunks/_061ph.1._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/node_modules_0hep.ny._.js")
R.c("server/chunks/[root-of-the-server]__0n8dqtr._.js")
R.c("server/chunks/_01_0w._._.js")
R.c("server/chunks/node_modules_next_dist_0k~eexk._.js")
R.c("server/chunks/_next-internal_server_app_api_calls_token_route_actions_008qh.t.js")
R.m(317016)
module.exports=R.m(317016).exports
